### PR TITLE
InfStones PR for bbntest-4

### PR DESCRIPTION
**Pull request by adam-infstones**
InfStones PR for bbn-test-4. Please review.

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @adam-infstones can you verify this? 
`[btc-staker] finality provider pk in tx 75ef424249a4b734ed730468387b33dfa596e1912dfa8b6ea4f36af488b2bcf0 do not match with flag 3b88d9cf5f52ab6ae4b5b25d6a8b3b779a2baa4bd5204f5a78ecd95e878361ea` 
Seems like a diff fp pk was used

**Comment by adam-infstones** [comment]
Working to verify now

**Comment by adam-infstones** [comment]
./eotsd verify-schnorr-sig /home/ubuntu/sample.txt --btc-pk 3b88d9cf5f52ab6ae4b5b25d6a8b3b779a2baa4bd5204f5a78ecd95e878361ea --signature 1db9c6e7e3b3debfa8e9e5bef425e2968b1f7f72fee811be51a5c6d7951b5c69b17447ac9145789a25b186ab958a801fc3ba583b77a8236444843f0eb446d58b
Verification is successful!

**Comment by RafilxTenfen** [comment]
> 75ef424249a4b734ed730468387b33dfa596e1912dfa8b6ea4f36af488b2bcf0

This is not the same as `btc_pk` inside your json file https://github.com/babylonchain/networks/pull/165/files#diff-399fbf6615a841e3364b0edf69bbb05561dabc17d74b3047cfcf2f130d2016f2R9

**Comment by adam-infstones** [comment]
Okay, so it should look like this or do I need to redo this whole thing? I have swapped out btc_pk to my finality provider pk. 

{
  "description": {
    "moniker": "InfStones",
    "identity": "E9B7CDC7623E0327",
    "website": "https://infstones.com/",
    "security_contact": "promit@infstones.com",
    "details": "InfStones is a Web3 native enterprise-grade Node-as-a-Service and institutional staking platform"
  },
  "btc_pk": "75ef424249a4b734ed730468387b33dfa596e1912dfa8b6ea4f36af488b2bcf0",
  "commission": "0.10",
  "deposit": {
    "tx_hash": "dc03deae40081c12bbccb1ba0235a0703ecf7eff33d59859cdc6ef253592c45f",
    "signed_tx": "02000000000101e504d5c0d9921a1e1adc618f5cd8533bf573643405e45c56ccc8e07cb25c9be00900000000fdffffff03554a4c00000000001600149b84b1c2dcd13ef26d02afe0e13cf921eb6570d280969800000000002251202c48b5d242b8b359db0fbcb605d3e7dab191998f0a25511c1d9851e81cd8c59f0000000000000000496a47626274340071e47cf1ad8e58e6182524369c9842d1be178f47912b92b8c40dfbb006afed3275ef424249a4b734ed730468387b33dfa596e1912dfa8b6ea4f36af488b2bcf0cd500247304402200d34856cdbdcd117aef86f0861bf1702c9cce90be0cca3d8f5790def71ac369f0220038ebaf81a9bd4e442184b1792472475d80d36e103e16e30c6fb31dea865ae3a01210271e47cf1ad8e58e6182524369c9842d1be178f47912b92b8c40dfbb006afed3200000000"
  }
}

**Comment by RafilxTenfen** [comment]
> Okay, I think I am just going to have to run through the process and submit a new PR. I will close this one out and work to get through the process and new PR submitted by end of day. Apologies for the confusion.

All good, you are probably going to need to ask for funds again @filippos47

**Pull request closed without merging**
