### PR TITLE
Add 01node finality provider

### PR DESCRIPTION
**Pull request by daemon2k3**

### CODE REVIEW

**Comment by daemon2k3** [comment]
Please retry merging - the transactions has 10 confirmations.

**Comment by daemon2k3** [comment]
I've added the correct sig file.

**Comment by snakeeeeeeeee** [comment]
> I've added the correct sig file.

@daemon2k3 hello brother, how did you solve this problem? I have also encountered

**Comment by daemon2k3** [comment]
For snakee - we've checked the signature by adding a btc-pk - and that doesn't use the key from eotsd. We had multiple keys setup. In short - generate a signature with a key and make sure it's the pk that's gonna be used for verification. That's how the check passes.

**Review by filippos47 — APPROVED** [review]

**Pull request merged**
