### PR TITLE
parameters: Add version v1

### PR DESCRIPTION
**Pull request by filippos47**
`v1` version of the global parameters takes effect at signet BTC height `198665` and introduces the following changes:
- Staking cap: Bumped from 5 to 50 signet BTC
- Bumps unbonding fee to 10k Satoshi
- Rotates the BTC keyring of one of the 3 Babylon Covenant Signers

### CODE REVIEW

**Review by fishermanymc — APPROVED** [review]

**Review by kwantam — COMMENTED** [review]
:+1: approved and applied

**Comment by liewhite** [comment]
CoinSummer Labs: approved and applied

**Comment by ajvpot** [comment]
Zellic updated and approved

**Review by dbkbali — COMMENTED** [review]
Approved and applied.

**Comment by antonio-altr** [comment]
AltLayer: approved and applied

**Comment by ivy191118** [comment]
RockX approved and applied

**Review by KonradStaniec — APPROVED** [review]

**Pull request merged**
