### PR TITLE
Register Staketab as a finality provider

### PR DESCRIPTION
**Pull request by duccas**

### CODE REVIEW

**Comment by duccas** [comment]
@vitsalis I want to clarify about the staking amount, does it have to be exactly 0.10 sBTC or a minimum of that much? So the probable reason is that I staked 0.15 sBTC?

**Comment by duccas** [comment]
Oh yeah, i see in the CI:
```[btc-staker] staking amount in tx 15000000 do not match with flag 10000000```

**Comment by duccas** [comment]
I think it should be ok?

**Comment by duccas** [comment]
Can you also give me an idea why my signature verification is failing? Because locally I'm successful!

My example:
```
eotsd sign-schnorr $HOME/$EOTSD_CONFIG/Staketab.json \
--home $HOME/$EOTSD_CONFIG \
--key-name $EOTSD_ACC \
--keyring-backend test
```
```
{
    "key_name": "eotsd",
    "pub_key_hex": "76cd2bea40e8226eb87cf5d3f07b66327fc8afc7c9d52e2e73bb711b9a6fd8e1",
    "signed_data_hash_hex": "398fd0c37ccea0ed982ef1f66155155152839b795d955292464c4334978b173c",
    "schnorr_signature_hex": "3aec21e36845e6d1ecd48c18613fcf458d0e0a91ead7ad3c82c4946ca822df23f127c8b49b56f11656666d928925cbf5596b1fd47cd2425f93a3e57aa38beefc"
}
```
Verification:
```
eotsd verify-schnorr-sig $HOME/$EOTSD_CONFIG/Staketab.json \
--keyring-backend test \
--btc-pk 76cd2bea40e8226eb87cf5d3f07b66327fc8afc7c9d52e2e73bb711b9a6fd8e1 \
--signature 3aec21e36845e6d1ecd48c18613fcf458d0e0a91ead7ad3c82c4946ca822df23f127c8b49b56f11656666d928925cbf5596b1fd47cd2425f93a3e57aa38beefc
```
```
Verification is successful!
```

image

**Comment by RafilxTenfen** [comment]
Yes, One thing was the file name, did not seem the same as the one on the PR

**Comment by duccas** [comment]
> Yes, One thing was the file name, did not seem the same as the one on the PR
> 
> The signed and submitted file needs to be exactly the same

I think it was because we were moving files to another machine to do a PR. Now we have signed and made a PR from the same machine and the signature is verified!

**Review by vitsalis — APPROVED** [review]
Thanks!

**Pull request merged**
