### PR TITLE
Register puckanode as a Finality Provider

### PR DESCRIPTION
**Pull request by Puckapao**
Register puckanode as a Finality Provider

### CODE REVIEW

**Comment by Puckapao** [comment]
Screenshot 2567-05-17 at 02 30 31
I would like to know why check on sig file is not passed. It passed when I verify here.

**Comment by Puckapao** [comment]
Any solution to this?

**Comment by Puckapao** [comment]
@vitsalis Good afternoon, do you have any solution to this? I still can sign new one and verify successfully.
```
{
  "key_name": "eotsd",
  "pub_key_hex": "1114f98294c1f59ef7134615c9080fe2e04b9662bb18cd8ddbbe5be77f746a06",
  "signed_data_hash_hex": "e75d6f1f767d919083e17302ede641189b860739d33d489644ceb3096837de0f",
  "schnorr_signature_hex": "9a1ea3133bdb88b9e50aea2dccfda6c83fb3e4cf19fb93586bfebf96be03fdf96d15f3e8f46bb96e3d55faefb7b96055e3ff6da5dc02f3a9fe1ec3f5954fb968"
}
```

```
eotsd verify-schnorr-sig /root/.eotsd/data/eots.db --btc-pk 1114f98294c1f59ef7134615c9080fe2e04b9662bb18cd8ddbbe5be77f746a06 --signature 9a1ea3133bdb88b9e50aea2dccfda6c83fb3e4cf19fb93586bfebf96be03fdf96d15f3e8f46bb96e3d55faefb7b96055e3ff6da5dc02f3a9fe1ec3f5954fb968
Verification is successful!
```

**Comment by Puckapao** [comment]
Finally all good

**Review by filippos47 — APPROVED** [review]
Thank you!

**Pull request merged**
