### PR TITLE
Register Staketab as a finality provider

### PR DESCRIPTION
**Pull request by duccas**

### CODE REVIEW

**Comment by vitsalis** [comment]
@duccas Signature and staking transaction seem to be invalid

**Comment by RafilxTenfen** [comment]
@duccas can you check if the `btc_pk` used to create the staking tx is the same as the one in the `.json` file ?

**Comment by duccas** [comment]
> @duccas can you check if the `btc_pk` used to create the staking tx is the same as the one in the `.json` file ?

We did the staking transactions according to this guide with the command below, is this wrong?
https://github.com/babylonchain/btc-staker/blob/1b1ea49d4e8421041e6748f537af6a9b252990a6/docs/create-phase1-staking.md

```
stakercli transaction create-phase1-staking-transaction \
  --staker-pk a77975899eededc731d80eee488b21fbee5715a16e3aba5ec83400c6d551af2c
  --staking-amount 15000000 --staking-time 52560 \
  --magic-bytes 62627434 \
  --finality-provider-pk 76cd2bea40e8226eb87cf5d3f07b66327fc8afc7c9d52e2e73bb711b9a6fd8e1 \
  --covenant-quorum 3 \
  --covenant-committee-pks 05149a0c7a95320adf210e47bca8b363b7bd966be86be6392dd6cf4f96995869 \
  --covenant-committee-pks e8d503cb52715249f32f3ee79cee88dfd48c2565cb0c79cf9640d291f46fd518 \
  --covenant-committee-pks fe81b2409a32ddfd8ec1556557e8dd949b6e4fd37047523cb7f5fefca283d542 \
  --covenant-committee-pks bc4a1ff485d7b44faeec320b81ad31c3cad4d097813c21fcf382b4305e4cfc82 \
  --covenant-committee-pks 001e50601a4a1c003716d7a1ee7fe25e26e55e24e909b3642edb60d30e3c40c1 \
  --network signet
  ```
  Our FP pubkey:
  ```
  pub_key_hex": "76cd2bea40e8226eb87cf5d3f07b66327fc8afc7c9d52e2e73bb711b9a6fd8e1"
  ```
  Our Staker key is:
  ```
  bitcoin-cli -signet \
-rpcuser=$BTC_USER \
-rpcpassword=$BTC_PASS \
-rpcport=38332 \
-rpcwallet=$BTC_WALLET_NAME \
getaddressinfo tb1qrus6f7gr4vlxyeyj7see3ad0y4gp6qtxxr0mds | jq -r '.pubkey[2:]'
```
```
a77975899eededc731d80eee488b21fbee5715a16e3aba5ec83400c6d551af2c
```

**Comment by RafilxTenfen** [comment]
> > @duccas can you check if the `btc_pk` used to create the staking tx is the same as the one in the `.json` file ?
> 
> We did the staking transactions according to this guide with the command below, is this wrong? https://github.com/babylonchain/btc-staker/blob/1b1ea49d4e8421041e6748f537af6a9b252990a6/docs/create-phase1-staking.md
> 
> ```
> stakercli transaction create-phase1-staking-transaction \
>   --staker-pk a77975899eededc731d80eee488b21fbee5715a16e3aba5ec83400c6d551af2c
>   --staking-amount 15000000 --staking-time 52560 \
>   --magic-bytes 62627434 \
>   --finality-provider-pk 76cd2bea40e8226eb87cf5d3f07b66327fc8afc7c9d52e2e73bb711b9a6fd8e1 \
>   --covenant-quorum 3 \
>   --covenant-committee-pks 05149a0c7a95320adf210e47bca8b363b7bd966be86be6392dd6cf4f96995869 \
>   --covenant-committee-pks e8d503cb52715249f32f3ee79cee88dfd48c2565cb0c79cf9640d291f46fd518 \
>   --covenant-committee-pks fe81b2409a32ddfd8ec1556557e8dd949b6e4fd37047523cb7f5fefca283d542 \
>   --covenant-committee-pks bc4a1ff485d7b44faeec320b81ad31c3cad4d097813c21fcf382b4305e4cfc82 \
>   --covenant-committee-pks 001e50601a4a1c003716d7a1ee7fe25e26e55e24e909b3642edb60d30e3c40c1 \
>   --network signet
> ```
> 


it is wrong, take a look [here](https://github.com/babylonchain/networks/blob/main/bbn-test-4/finality-providers/README.md#2-deposit-self-lock-btc)

Where it specifies that the flags
```shell
  --covenant-committee-pks=50929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0 \
  --covenant-quorum=1 --network=signet
```

since this is a lock only tx, the committee is a key that no one has access to withdraw and the funds will only be available in 52560 sBTC blocks '-'

@filippos47 could you send 0.1sBTC for Staketab again?

**Comment by duccas** [comment]
@RafilxTenfen  I get your point, the documentation is very extensive and the commands are different in some places. I thought that might be the reason.

**Comment by RafilxTenfen** [comment]
@duccas my recomendation is to start from scratch to avoid missing any step

**Comment by duccas** [comment]
> @duccas my recomendation is to start from scratch to avoid missing any step

The error is clear. Thank you!

**Pull request closed without merging**
