### PR TITLE
bbn-test-4: Add Cap-4

### PR DESCRIPTION
**Pull request by filippos47**

### CODE REVIEW

**Review by KonradStaniec — APPROVED** [review]

**Review by vitsalis — APPROVED** [review]

**Comment by liewhite** [comment]
CoinSummerLabs params downloaded and applied

**Comment by antonio-altr** [comment]
AltLayer params downloaded and applied

**Comment by ivy191118** [comment]
RockX params downloaded and applied

**Comment by dbkbali** [comment]
Informal Staking - params downloaded and applied

**Comment by kwantam** [comment]
cubist - params downloaded and applied

**Comment by zellic-audit** [comment]
Zellic - params downloaded and applied

**Pull request merged**
