### PR TITLE
Add P-OPSTeam provider

### PR DESCRIPTION
**Pull request by rooiie**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @rooiie can you verify if the json file submitted in the PR is exactly the same one signed ? not just the content, but the metadata and everything?

**Comment by rooiie** [comment]
@RafilxTenfen how can i check that?

**Comment by RafilxTenfen** [comment]
> @RafilxTenfen how can i check that?

you check locally with `https://github.com/babylonchain/networks/blob/main/bbn-test-4/finality-providers/scripts/verify-new-fp-offchain.sh`

but, also just make sure the `.json` you submitted in this PR is not being created again in a different environment

**Comment by rooiie** [comment]
@RafilxTenfen 
getting below

fp moniker: P-OPS Team
fp commission: 0.05
fp nickname: P-OPSTeam
fp btcpk: c5ac8b06424fe09787bfd2b93ab2b002775e913ef4134d2a012414764203a370
fp signature: 7c8fe14bef4e7d05a501b569a389983050dadff1da1c0ce3929c95a82b289ee933e816fade6725a61a728cb05e181952873fa50112597a3a5cbac667fe7a6130
eotsd verify signature
[eotsd] invalid signature

when doing the schnorr it says successfull

**Comment by RafilxTenfen** [comment]
if you signed the json in some specific environment, make sure to submit the file to github from that environment 
Otherwise the json will be different and the CI fails the verification

**Comment by rooiie** [comment]
> if you signed the json in some specific environment, make sure to submit the file to github from that environment Otherwise the json will be different and the CI fails the verification

Just to be sure 

btc_pk is the public key the same as the one used in staker-cli create-phase1-staking-transaction --staker-pk

or should that be the address which signed the tx on chain?

**Comment by rooiie** [comment]
@RafilxTenfen it looks like it worked now ;-)
It was due to the fact i did the schnor on an empty file. 
i dont know where that glitch came to me ;-)

**Pull request merged**
