### PR TITLE
Create NODERS.json

### PR DESCRIPTION
**Pull request by aleksandrnoders**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @aleksandrnoders 
The following CI failures and probably reasons: 
- ci/circleci: verify-sig = The signed json file is not exactly the same submitted in PR, it needs to be exactly the same, not just the content
- ci/circleci: verify-onchain-BTC-tx = Just need to rerun and will pass
- ci/circleci: verify-offchain-signed-tx = `[btc-staker] staking amount in tx 1000000 is less than the min-staking-amount in flag 10000000`

**Comment by nodersteam** [comment]
> Hey @aleksandrnoders The following CI failures and probably reasons:
> 
> * ci/circleci: verify-sig = The signed json file is not exactly the same submitted in PR, it needs to be exactly the same, not just the content
> * ci/circleci: verify-onchain-BTC-tx = Just need to rerun and will pass
> * ci/circleci: verify-offchain-signed-tx = `[btc-staker] staking amount in tx 1000000 is less than the min-staking-amount in flag 10000000`

Hey!
I didn’t find a faucet where I can get enough BTC, maybe you can help with this?

**Comment by RafilxTenfen** [comment]
> Hey! I didn’t find a faucet where I can get enough BTC, maybe you can help with this?

Can you share your sBTC address? 

@filippos47

**Comment by nodersteam** [comment]
> > Hey! I didn’t find a faucet where I can get enough BTC, maybe you can help with this?
> 
> Can you share your sBTC address?
> 
> @filippos47

`tb1q0qazh6hdv9fn6ww2405ck5npksehnjz9wuu3v9`

**Comment by jwelrynewone** [comment]
@RafilxTenfen if you dont mind, i'd ask 0.1 sbtc as well. thank you!

``tb1qh72n4qe9fxjuj9uk6et6lnm26xfesld06wt34h``

**Comment by nodersteam** [comment]
> > Hey! I didn’t find a faucet where I can get enough BTC, maybe you can help with this?
> 
> Can you share your sBTC address?
> 
> @filippos47

While you have not sent tokens - I have changed the address for receiving tokens

Will we have time to receive tokens before the start?

**Comment by vitsalis** [comment]
Hi @nodersteam , apologies for the late reply, we do not provide signet tokens based on GitHub requests.

**Pull request closed without merging**
