### PR TITLE
bbn-test-4: Add Cap-5

### PR DESCRIPTION
**Pull request by filippos47**

### CODE REVIEW

**Review by vitsalis — APPROVED** [review]

**Comment by Exubient** [comment]
AltLayer: approved and applied

**Comment by liewhite** [comment]
CoinSummerLabs: approved and applied

**Comment by zellic-audit** [comment]
Zellic approved and applied.

**Comment by dbkbali** [comment]
Informal Staking params downloaded and applied 🚀

**Comment by kwantam** [comment]
Cubist: params downloaded and applied.

**Comment by AlexRockX** [comment]
RockX params downloaded and applied

**Pull request merged**
