### PR TITLE
Add FP for SpiderPool

### PR DESCRIPTION
**Pull request by xianxiongwang**

### CODE REVIEW

**Comment by xianxiongwang** [comment]
Why is there error in parms-parser CI? I run go test in parameter folder locally and successed...Please let me know if I do something wrong, thanks.

**Comment by vitsalis** [comment]
Hi @xianxiongwang, can you please rebase to `main`?

**Comment by xianxiongwang** [comment]
Rebased and all tests passed, thanks!

**Review by vitsalis — APPROVED** [review]
Thanks!

**Pull request merged**
