### PR TITLE
Finality Provider for Pier Two

### PR DESCRIPTION
**Pull request by avinava-mycelium**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @avinava-mycelium there is a missmatch for the signature, can you make sure the .json file provided is exactly the one you signed? Not just the same content, but the exact same file

**Comment by avinava-mycelium** [comment]
> Hey @avinava-mycelium there is a missmatch for the signature, can you make sure the .json file provided is exactly the one you signed? Not just the same content, but the exact same file

Hey @RafilxTenfen 👋 

Thanks for the revert. The .json file was manually created and added as per the instructions? Do we need to generate this content from somewhere?


Also, the value, `signed_tx` was generated after running the [fundrawtransaction](https://github.com/babylonchain/btc-staker/blob/main/docs/create-phase1-staking.md#fund-raw-transaction) method

`bitcoin-cli -signet \
  -rpcuser=<user> \
  -rpcpassword=<password> \
  -rpcport=38332 \
  -rpcwallet=<wallet> \
  fundrawtransaction <staking_tx_hex>
{
  "hex": "0200000001542c69102cfee8147110ca1918d8c6d1b8c88df0e55b6412db8f77cd04404a820000000000fdffffff03554a4c000000000016001411f387f90aec58c27b013e51093640438171fe6a8096980000000000225120c00963f19bce203582c358337efdef0912ba3cfd71d992c989c867f1768f49790000000000000000496a476262743400b43e502c5df751a79f2b1b077a7d1fc887a010944d51f04fb03c27c6fa14d2de62bdf47dcd57613c37ee36f0aafa468206e4affa2d9d64f55786be54fe198040cd5000000000",
  "fee": 0.00000235,
  "changepos": 0
}`


Thanks

**Comment by RafilxTenfen** [comment]
Usually when the signature (bbn-test-4/finality-providers/sigs/PierTwo.sig) fails is because the signed file (bbn-test-4/finality-providers/registry/PierTwo.json) in the repository is not the same as the one you used to sign 

Sometimes finality providers just copy the content of the file over and that is not correct, as to generate the signature eotsd doesn't just read the content but the entire file with metadata and everything...

**Comment by avinava-mycelium** [comment]
Thanks for your response.
When you say , "_just copy the content of the file over and that is not correct_" , I am unsure about which file is being referred to here.

I ran the **bitcoin-cli** tool to generate the signature and it was just this output as mentioned below and no file.

Here is the command:
eotsd sign-schnorr /path/to/data/file --home /path/to/eotsd/home/ --btc-pk 62bdf47dcd57613c37ee36f0aafa468206e4affa2d9d64f55786be54fe198040 --keyring-backend file
Enter keyring passphrase (attempt 1/3): <passphrase>
{
    "key_name": "",
    "pub_key_hex": "62bdf47dcd57613c37ee36f0aafa468206e4affa2d9d64f55786be54fe198040",
    "signed_data_hash_hex": <signed_data_hash_hex>,
    "schnorr_signature_hex": "30613b14d3ea44d4f8a5e158a85b14fc4546706eb2057730b5db7a23711ba9f49f8e55893bd3bd9a4cf590cf0e6b1dcb5862f8084cf5b2b339d910c21371d684"
}

I have provided the **schnorr_signature_hex** in the PierTwo.sig file

I have also verified the signature and it was successful.

Can you please help me understand which file is being referred?

**Comment by RafilxTenfen** [comment]
> Thanks for your response. When you say , "_just copy the content of the file over and that is not correct_" , I am unsure about which file is being referred to here.
> 
> I ran the **bitcoin-cli** tool to generate the signature and it was just this output as mentioned below and no file.
> 
> Here is the command: eotsd sign-schnorr /path/to/data/file --home /path/to/eotsd/home/ --btc-pk 62bdf47dcd57613c37ee36f0aafa468206e4affa2d9d64f55786be54fe198040 --keyring-backend file Enter keyring passphrase (attempt 1/3): { "key_name": "", "pub_key_hex": "62bdf47dcd57613c37ee36f0aafa468206e4affa2d9d64f55786be54fe198040", "signed_data_hash_hex": <signed_data_hash_hex>, "schnorr_signature_hex": "30613b14d3ea44d4f8a5e158a85b14fc4546706eb2057730b5db7a23711ba9f49f8e55893bd3bd9a4cf590cf0e6b1dcb5862f8084cf5b2b339d910c21371d684" }
> 
> I have provided the **schnorr_signature_hex** in the PierTwo.sig file
> 
> I have also verified the signature and it was successful.
> 
> Can you please help me understand which file is being referred?

Yes, the file in `bbn-test-4/finality-providers/registry/PierTwo.json` needs to be the one you signed with the command `eotsd sign-schnorr` if you run `eotsd sign-schnorr` in a different system and just copy the content of that file to this Pull Request, the verification will fail

It needs to be exactly the signed file that you used in this
> Here is the command: eotsd sign-schnorr /path/to/data/file --home /path/to/eotsd/home/ --btc-pk 62bdf47dcd57613c37ee36f0aafa468206e4affa2d9d64f55786be54fe198040 --keyring-backend file

**Comment by avinava-mycelium** [comment]
Ok, so if I understand correctly we need to submit the pull request from the same system where these commands are being run from and not from any arbitrary system?
In my case, I ran the commands in an internal GCP server and then forked this repo in my laptop and pushed the above changes after modifying the required files. That won't work?

I should ideally fork and clone the repo in the same internal server and then raise a PR from that system , itself?

**Comment by RafilxTenfen** [comment]
> Ok, so if I understand correctly we need to submit the pull request from the same system where these commands are being run from and not from any arbitrary system? In my case, I ran the commands in an internal GCP server and then forked this repo in my laptop and pushed the above changes after modifying the required files. That won't work?
> 
> I should ideally fork and clone the repo in the same internal server and then raise a PR from that system , itself?

What I am saying is, if you only copy the CONTENT of the file it will fail, you need to copy the entire file with metadata and everything... 
The easiest way is to push the signed file and the signature directly from the GCP in my opinion

**Comment by avinava-mycelium** [comment]
Right that makes sense,
I will close this PR and raise a new one in that case

This new one will be raised directly from the GCP server

**Pull request closed without merging**
