### PR TITLE
DanielX provider

### PR DESCRIPTION
**Pull request by Daniiel-X**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @Daniiel-X the registration is turned off after PR #360 
You can still be a finality provider and stake to your FP

**Comment by Daniiel-X** [comment]
So I wont be able to be merged to the main branch? Will this application be opened again in the future?

**Comment by RafilxTenfen** [comment]
Maybe for another testnet, but the setup might also be different

**Comment by Daniiel-X** [comment]
Okay, thank you, hope you have a great day!

**Pull request closed without merging**
