### PR TITLE
relocate web3 json

### PR DESCRIPTION
**Pull request by liam-icheng-lai**

### CODE REVIEW

**Review by RafilxTenfen — APPROVED** [review]
CI does not check if the file is not inside registry, any idea to solve this @liam-icheng-lai  ?

**Comment by liam-icheng-lai** [comment]
We can work on this verification

**Comment by fuleru** [comment]
Could you please tell me when it will appear in the https://btcstaking.testnet.babylonchain.io list?

**Comment by liam-icheng-lai** [comment]
It's up and there.

**Pull request merged**
