### PR TITLE
Register Coinage x DAIC as Finality Provider

### PR DESCRIPTION
**Pull request by DAICers**

### CODE REVIEW

**Comment by vitsalis** [comment]
Seems that the staking amount in the deposit is not the `0.1 signet BTC` it should be.

**Comment by DAICers** [comment]
We thought 0.1 signet BTC is the min Staking amount. 

I just saw that it doesn't count for staking - so I think that was bad for us.

**Comment by DAICers** [comment]
Would it be still possible to merge this PR?

**Comment by DAICers** [comment]
@vitsalis can we still move forward or do we need to create a new  finality provider?

**Review by vitsalis — APPROVED** [review]
It's ok, thank you!

**Pull request merged**
