### PR TITLE
HeatherYOLO BBN4 provider

### PR DESCRIPTION
**Pull request by JoelryYOLO**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
Hey @JoelryYOLO the file `bbn-test-4/finality-providers/HeatherYOLO.json` should be inside registry `bbn-test-4/finality-providers/registry/HeatherYOLO.json` like the others

**Comment by JoelryYOLO** [comment]
Fixed it, thank you!

**Comment by RafilxTenfen** [comment]
@JoelryYOLO the signature should be `bbn-test-4/finality-providers/sigs/HeatherYOLO.sig` instead of `bbn-test-4/finality-providers/sigs/HeatherYOLO.json`

**Comment by JoelryYOLO** [comment]
Sorry, but now should be okay 100%...

**Review by liam-icheng-lai — APPROVED** [review]

**Pull request merged**
