### PR TITLE
Adding StakeLab finality provider

### PR DESCRIPTION
**Pull request by zdeadex**

### CODE REVIEW

**Comment by RafilxTenfen** [comment]
@zdeadex can you provide the signature for the json? 
`signature file bbn-test-4/finality-providers/registry/../sigs/StakeLab.sig not found`

**Comment by zdeadex** [comment]
@RafilxTenfen done

**Comment by RafilxTenfen** [comment]
@zdeadex something is wrong, can you verify? 
image

**Comment by zdeadex** [comment]
Hey @RafilxTenfen changed one part of the "details" part as there was a "-" on it to see if it was the problem
But on my side both are correct, so lemme know if it solved the problem with these two new files

**Comment by RafilxTenfen** [comment]
This is weird, it is not finding the main on tree, can you run the script `bbn-test-4/finality-providers/scripts/verify-new-fp-offchain.sh` locally and it works?

**Pull request closed without merging**
