### PR TITLE
Add InfraSingularity FP

### PR DESCRIPTION
**Pull request by benwin-is**

### CODE REVIEW

**Comment by benwin-is** [comment]
Hi @RafilxTenfen I think it might be because of the format/extra-space issue. I will fix and commit it again

**Comment by RafilxTenfen** [comment]
@benwin-is Still failing the signature 
image

My best guess is still the signed json file is not the same as the one in PR

**Comment by benwin-is** [comment]
I copied and pasted the JSON from the server to the local VS code. Is there a better way to do it?

**Comment by RafilxTenfen** [comment]
> I copied and pasted the JSON from the server to the local VS code. Is there a better way to do it?

this is the wrong way to do it, the signature signs the entire file, not just the content of the file, you need to use exactly the same file signed

**Comment by benwin-is** [comment]
Thank you so much for the correction. Will do that

**Comment by benwin-is** [comment]
Could you please check once again @RafilxTenfen

**Review by liam-icheng-lai — APPROVED** [review]

**Pull request merged**
