### PR TITLE
Add NodeStake as Finality Provider 

### PR DESCRIPTION
**Pull request by nodestake**

### CODE REVIEW

**Comment by filippos47** [comment]
Hey team! I see that your staking amount is 0.0001 Signet BTC:
```
[btc-staker] staking amount in tx 10000 is less than the min-staking-amount in flag 10000000
```

Also, your signature is invalid.

**Comment by nodestake** [comment]
Hi Can you fund 0.1 signet BTC to our address tb1qhy2v0xjz97ak8yxugmsvhx75r0j43a675wgae4

**Comment by nodestake** [comment]
Hi @filippos47 We have update the PR
1.  Stake 10000000
2. Sign the Finality Provider information

**Review by filippos47 — APPROVED** [review]
Thanks team!

**Pull request merged**
